# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Zonescan
                                 A QGIS plugin
 Point selection, buffer creation, intersection analysis, and reporting
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-22
        copyright            : (C) 2025 by Adnan Benaboud
        email                : adnanbenaboud5@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Zonescan class from file Zonescan.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zone_scan import Zonescan
    return Zonescan(iface)
